# Generated by Django 4.2.16 on 2024-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='q5j_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
