# Generated by Django 4.2.16 on 2024-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resposta_q5j_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='q5j',
            field=models.TextField(blank=True, null=True),
        ),
    ]
