# Generated by Django 4.2.16 on 2024-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resposta_q5j'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='q1',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='q2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='q3',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='q4',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='q5j',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
